version: '3.8'
services:
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - app
            - db
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d
    db:
        image: mysql
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/logs:/var/log/mysql
        environment:
            - MYSQL_DATABASE=job_search_app
            - MYSQL_ROOT_PASSWORD=password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: pma
        restart: always
        ports:
            - "3400:80"
        depends_on:
            - db
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/
        ports:
            - "8999:9000"
        working_dir: /var/www/
